#!/bin/bash

# *** Check if file is sourced
(return 0 2>/dev/null) && poet_sourced=1 || poet_sourced=0

if [ "$poet_sourced" -eq 0 ]; then
    echo "This script must be sourced"
    exit 1
fi

server_url=$1

[ -z "$server_url" ] && {
    /bin/echo "Enter a server url"
    return 1
}

/bin/echo "* Install poet"
/bin/mkdir -p "$HOME"/.local/bin && cd "$HOME"/.local/bin || return 1
[ -d "./poet" ] || /bin/git clone git@"$server_url":/opt/global/bin-poet poet
# shellcheck disable=SC2016
/bin/grep 'export PATH="$PATH:$HOME/.local/bin/poet"' "$HOME"/.bashrc || {
    /bin/echo 'export PATH="$PATH:$HOME/.local/bin/poet"' >>"$HOME"/.bashrc
}

/bin/echo "* Install installer"
cd "$HOME" || return 1
[ -d "./poet-install" ] || /bin/git clone git@"$server_url":/opt/global/poet-install

/bin/echo "* Install poet-install inventory"
cd "$HOME" || return 1
mkdir -p "$HOME"/01_Inventory && cd "$HOME"/01_Inventory || return 1
[ -d "./install" ] || /bin/git clone git@"$server_url":/opt/global/install-inventory install

/bin/echo "* Run poet for installer"
# shellcheck disable=SC1091
. "$HOME"/.profile
# shellcheck disable=SC1091
. "$HOME"/.bashrc
cd "$HOME" || return 1
# shellcheck disable=SC1091
. "$HOME"/.local/bin/poet/poet installd
